repos:
-   repo: https://github.com/python-poetry/poetry
    rev: '1.8.4'  # add version here
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
    -   id: poetry-export
    -   id: poetry-install